// This file was autogenerated by calcdeps.py
goog.addDependency("../../../../app/app.js", ['hedgehog.Application'], ['goog.dom']);
goog.addDependency("../../../../app/deps.js", [], []);
goog.addDependency("../../../../app/externs.js", [], []);
goog.addDependency("../../../../app/requirements.js", [], ['hedgehog.Application']);
